services:
  forcoven:
    image: casmith/forcoven:0.1.0
    ports:
      - "80:80"
    # volumes:
      # - ./data/nginx:/etc/nginx/conf.d
      # - ./data/certbot/conf:/etc/letsencrypt
      # - ./data/certbot/www:/var/www/certbot
    restart: always
  nginx:
    image: nginx:1.15-alpine
    ports:
      # - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d:ro
      - ./data/certbot/www:/var/www/certbot:ro
      - ./data/certbot/conf:/etc/letsencrypt:ro
    restart: always
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt:rw
      - ./data/certbot/www:/var/www/certbot:rw
        #entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    restart: always
